#!/bin/sh

check() {
	i=0
	for prefix in "$@"; do
		out=$(./seq "$prefix$n" "$prefix$n" 2>&1)
		if [ "$prefix" = - ] && [ "$n" != 0 ]; then
			expected="minus $expected"
		fi

		if [ "$out" = "$expected" ]; then
			printf 'ok %s %s\n' "$i" "$expected"
		else
			printf 'not ok %s %s : %s\n' "$i" "$expected" "$out"
			exit=1
		fi
		: $(( i = i + 1 ))
	done
}

exit=0
while read -r n expected; do
	case $n in
	-*|9223372036854775808)
		printf '1..1\n'
		check ''
		;;
	*)
		printf '1..2\n'
		check '' -
		;;
	esac
done <<-'EOF'
	0	zero
	1	one
	2	two
	10	ten
	12	twelve
	23	twenty-three
	44	forty-four
	100	one hundred
	101	one hundred and one
	110	one hundred and ten
	100000	one hundred thousand
	100001	one hundred thousand one
	123456	one hundred and twenty-three thousand four hundred and fifty-six
	1000000	one million
	1000001	one million one
	1100001	one million one hundred thousand one
	9223372036854775807	nine quintillion two hundred and twenty-three quadrillion three hundred and seventy-two trillion thirty-six billion eight hundred and fifty-four million seven hundred and seventy-five thousand eight hundred and seven
	-9223372036854775808	minus nine quintillion two hundred and twenty-three quadrillion three hundred and seventy-two trillion thirty-six billion eight hundred and fifty-four million seven hundred and seventy-five thousand eight hundred and eight
	9223372036854775808	seq: start is too large: 9223372036854775808
	-9223372036854775809	seq: start is too small: -9223372036854775809
EOF

exit "$exit"
